<?php
/**
 * @var $block \Razoyo\AnimalProfile\Block\Profile\Photo
 */
?>
<p><?= $block->getGreeting() ?></p>
<div id="animalid-photo"></div>
<label for="animalid-photo-picker">
    Change animal photo:
    <select name="animalid-photo-picker" id="animalid-photo-picker">
        <option value="cat" selected>Cat</option>
        <option value="dog">Dog</option>
        <option value="llama">Llama</option>
        <option value="anteater">Anteater</option>
    </select>
</label>
<script>
    require(['jquery', 'domReady!'], function ($) {
        function loadAnimalidPhoto(type) {
            return $.ajax({
                url: '<?= $block->getPhotoUrl() ?>',
                data: { animalIdType: type },
                type: 'GET'
            }).done(
                function (response) {
                    console.log(response);
                    const photoImg = document.createElement('img'); 
                    photoImg.alt = 'Profile photo';
                    photoImg.src = response.photo;

                    const photoDiv = document.getElementById('animalid-photo');
                    if (photoDiv) {
                        while (photoDiv.firstChild) {
                            photoDiv.removeChild(photoDiv.firstChild);
                        }
                        photoDiv.appendChild(photoImg);
                    }
                }
            );
        }
        const pickerOpt = $('#animalid-photo-picker');
        pickerOpt.val('<?= $block->getPhotoFromSession() ?>');
        loadAnimalidPhoto('<?= $block->getPhotoFromSession() ?>');
        pickerOpt.on('change', function() {
            const opt = $(this).val();
            console.log(opt);
            return loadAnimalidPhoto(opt);
        });
    });
</script>
